### ISSUE TITLE
Running on RTX 3090: nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by entmike** [jeffheaton/docker-stylegan2-ada#1]
**Environment:**
- Linux (Unraid distribution)
- RTX 3090

`nvidia-smi` output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
| 60%   51C    P2   299W / 300W |   4651MiB / 24268MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Docker command:**

```
docker run --rm --gpus device=0 -it -u $(id -u):$(id -g) -v /mnt/user/appdata/stylegan2-ada/:/mnt heatonresearch/stylegan2-ada /bin/bash
```

**Python command:**
```
python train.py --gpus=1 --data=/mnt/datasets/shoes-1024b --kimg=10000 --outdir=/mnt/shoes-1024-results --aug=ada
```

**Error:**

```
Training options:
{
  "G_args": {
    "func_name": "training.networks.G_main",
    "fmap_base": 16384,
    "fmap_max": 512,
    "mapping_layers": 2,
    "num_fp16_res": 4,
    "conv_clamp": 256
  },
  "D_args": {
    "func_name": "training.networks.D_main",
    "mbstd_group_size": 4,
    "fmap_base": 16384,
    "fmap_max": 512,
    "num_fp16_res": 4,
    "conv_clamp": 256
  },
  "G_opt_args": {
    "beta1": 0.0,
    "beta2": 0.99,
    "learning_rate": 0.002
  },
  "D_opt_args": {
    "beta1": 0.0,
    "beta2": 0.99,
    "learning_rate": 0.002
  },
  "loss_args": {
    "func_name": "training.loss.stylegan2",
    "r1_gamma": 52.4288
  },
  "augment_args": {
    "class_name": "training.augment.AdaptiveAugment",
    "tune_heuristic": "rt",
    "tune_target": 0.6,
    "apply_func": "training.augment.augment_pipeline",
    "apply_args": {
      "xflip": 1,
      "rotate90": 1,
      "xint": 1,
      "scale": 1,
      "rotate": 1,
      "aniso": 1,
      "xfrac": 1,
      "brightness": 1,
      "contrast": 1,
      "lumaflip": 1,
      "hue": 1,
      "saturation": 1
    }
  },
  "num_gpus": 1,
  "image_snapshot_ticks": 50,
  "network_snapshot_ticks": 50,
  "train_dataset_args": {
    "path": "/mnt/datasets/shoes-1024b",
    "max_label_size": 0,
    "resolution": 1024,
    "mirror_augment": false
  },
  "metric_arg_list": [
    {
      "name": "fid50k_full",
      "class_name": "metrics.frechet_inception_distance.FID",
      "max_reals": null,
      "num_fakes": 50000,
      "minibatch_per_gpu": 8,
      "force_dataset_args": {
        "shuffle": false,
        "max_images": null,
        "repeat": false,
        "mirror_augment": false
      }
    }
  ],
  "metric_dataset_args": {
    "path": "/mnt/datasets/shoes-1024b",
    "max_label_size": 0,
    "resolution": 1024,
    "mirror_augment": false
  },
  "total_kimg": 10000,
  "minibatch_size": 4,
  "minibatch_gpu": 4,
  "G_smoothing_kimg": 1.25,
  "G_smoothing_rampup": 0.05,
  "run_dir": "/mnt/shoes-1024-results/00000-shoes-1024b-auto1-kimg10000-ada"
}

Output directory:  /mnt/shoes-1024-results/00000-shoes-1024b-auto1-kimg10000-ada
Training data:     /mnt/datasets/shoes-1024b
Training length:   10000 kimg
Resolution:        1024
Number of GPUs:    1

Creating output directory...
Loading training set...
Image shape: [3, 1024, 1024]
Label shape: [0]

Constructing networks...
Setting up TensorFlow plugin "fused_bias_act.cu": Compiling... Failed!
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    main()
  File "train.py", line 553, in main
    run_training(**vars(args))
  File "train.py", line 451, in run_training
    training_loop.training_loop(**training_options)
  File "/home/stylegan2-ada/training/training_loop.py", line 123, in training_loop
    Gs = G.clone('Gs')
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 457, in clone
    net.copy_vars_from(self)
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 490, in copy_vars_from
    src_net._get_vars()
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 297, in _get_vars
    self._vars = OrderedDict(self._get_own_vars())
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 286, in _get_own_vars
    self._init_graph()
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 151, in _init_graph
    out_expr = self._build_func(*self._input_templates, **build_kwargs)
  File "/home/stylegan2-ada/training/networks.py", line 231, in G_main
    num_layers = components.synthesis.input_shape[1]
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 232, in input_shape
    return self.input_shapes[0]
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 219, in input_shapes
    self._input_shapes = [t.shape.as_list() for t in self.input_templates]
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 267, in input_templates
    self._init_graph()
  File "/home/stylegan2-ada/dnnlib/tflib/network.py", line 151, in _init_graph
    out_expr = self._build_func(*self._input_templates, **build_kwargs)
  File "/home/stylegan2-ada/training/networks.py", line 439, in G_synthesis
    x = layer(x, layer_idx=0, fmaps=nf(1), kernel=3)
  File "/home/stylegan2-ada/training/networks.py", line 392, in layer
    x = modulated_conv2d_layer(x, dlatents_in[:, layer_idx], fmaps=fmaps, kernel=kernel, up=up, resample_kernel=resample_kernel, fused_modconv=fused_modconv)
  File "/home/stylegan2-ada/training/networks.py", line 105, in modulated_conv2d_layer
    s = apply_bias_act(s, bias_var='mod_bias', trainable=trainable) + 1 # [BI] Add bias (initially 1).
  File "/home/stylegan2-ada/training/networks.py", line 50, in apply_bias_act
    return fused_bias_act(x, b=tf.cast(b, x.dtype), act=act, gain=gain, clamp=clamp)
  File "/home/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 72, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain, clamp=clamp)
  File "/home/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 132, in _fused_bias_act_cuda
    cuda_op = _get_plugin().fused_bias_act
  File "/home/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 18, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/home/stylegan2-ada/dnnlib/tflib/custom_ops.py", line 159, in get_plugin
    _run_cmd(nvcc_cmd + ' "%s" --shared -o "%s" --keep --keep-dir "%s"' % (cuda_file, tmp_file, tmp_dir))
  File "/home/stylegan2-ada/dnnlib/tflib/custom_ops.py", line 69, in _run_cmd
    raise RuntimeError('NVCC returned an error. See below for full command line and output log:\n\n%s\n\n%s' % (cmd, output))
RuntimeError: NVCC returned an error. See below for full command line and output log:

nvcc --compiler-options '-fPIC' --compiler-options '-I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0' --linker-options '-L/usr/local/lib/python3.6/dist-packages/tensorflow -l:libtensorflow_framework.so.1' --gpu-architecture=sm_86 --use_fast_math --disable-warnings --include-path "/usr/local/lib/python3.6/dist-packages/tensorflow/include" --include-path "/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive/src" --include-path "/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/com_google_absl" --include-path "/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/eigen_archive" 2>&1 "/home/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.cu" --shared -o "/tmp/tmp29zryx70/fused_bias_act_tmp.so" --keep --keep-dir "/tmp/tmp29zryx70"

nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'
```

**Comment by maxdengmd** [comment]
Getting the same error. Were you ever able to figure this out?

**Comment by 8secz-johndpope** [comment]
Have a go with this updated base image. 
https://github.com/jeffheaton/docker-stylegan2-ada/pull/2

beward of base image you can find the latest here
https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow


let me know if it works. 

N.B. it's possible to get around tensorflow1 I'm running stylegan2 on my host. 
this repo I upgraded / it's using tf2 in compatibility mode / there's a docker file too. 
https://github.com/johndpope/stylegan2-ada

Strangely - I am seeing  'sm_86' is not defined for option 'gpu-architecture' for tf2 -
I upgraded it using **pip install tf-nightly-gpu**      but now seeing -
 RuntimeError: NVCC returned an error. /usr/include/c++/10/chrono:428:27: internal compiler error: Segmentation fault


tensorflow-gpu @ https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.5.0-cp38-cp38-
tf-nightly-gpu==2.7.0.dev20210630





UPDATE- 
ok going in circles but I believe the root of this issue is related to misalignment of cudatoolkit +  cuDnn 
https://developer.nvidia.com/rdp/cudnn-download

**Comment by jeffheaton** [comment]
Thanks, merged the pull request
